name: Docs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  sync-docs:
    name: Check docs sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Sync docs
      run: make sync-docs
