name: Docs
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ] # TODO
  pull_request:
    branches: [ main ] # TODO
jobs:
  sync-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
    - name: 'Regenerate Docs'
      run: make sync-docs
    - id: date
      run: echo "date=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: "chore: API docs sync"
        body: |
          Automated pull request to sync docs for:
          - Console operator
          - Deployment operator
          - Liquid filters
        commit-message: sync docs
        branch: docs-${{steps.date.outputs.date}}
        labels: documentation
        base: az-cli-docs # TODO main
