name: Docs
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ] # TODO
  pull_request:
    branches: [ main ] # TODO
jobs:
  sync-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Sync docs
      run: make sync-docs
    - name: Save date
      id: date
      run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        title: "chore: API documentation sync"
        body: |
          Automated pull request to sync docs for:
          - Console operator
          - Deployment operator
          - Liquid filters
        commit-message: sync docs
        branch: docs-${{steps.date.outputs.date}}
        labels: documentation
        base: az-cli-docs # TODO main
#    - name: Auto-approve
#      if: steps.cpr.outputs.pull-request-operation == 'created'
#      run: gh pr review --approve "${{ steps.cpr.outputs.pull-request-number }}"
#      env:
#        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Enable pull request auto-merge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: squash
